[info]
mainnet = true
telegram = true
voting_power_changes = 10
blocks_missed_in_a_row = 10
peers_count = 10
[[node]]
role = "validator"
rpc = "http://1.2.3.4:26657"
network_monitoring_enabled = true
[[node]]
role = "sentry"
rpc = "http://2.3.4.5:26657"
network_monitoring_enabled = true
[[node]]
role = "sentry"
rpc = "http://3.4.5.6:26657"
network_monitoring_enabled = true
[[node]]
role = "sentry"
rpc = "http://7.8.9.1:26657"
network_monitoring_enabled = false